
package vista;

import java.awt.Color;
import java.awt.Dimension;
import static java.awt.GridBagConstraints.BOTH;
import javax.swing.JDesktopPane;

/**
 *
 * @author Admin
 */
public class FrmMenu extends javax.swing.JFrame {
    
    public static JDesktopPane jDesktopPane_menu;
    
    public static FrmMenu fm;
    
    public FrmMenu() {
        initComponents();
        setSize(new Dimension (1200, 700));
        setExtendedState(this.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        setTitle("Sistema de gestion");
        
        setLayout(null);
        jDesktopPane_menu = new JDesktopPane();
        
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.jDesktopPane_menu.setBounds(0, 0, ancho, (alto - 110));
        jDesktopPane_menu.setBackground(Color.LIGHT_GRAY); 

        

        this.add(jDesktopPane_menu);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu5 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuGestionarUsuario = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItemNuevoUsuario = new javax.swing.JMenuItem();
        jMenuGestionarCategorias = new javax.swing.JMenu();
        jMenuItemGestionarCategoria = new javax.swing.JMenuItem();
        jMenuItemNuevaCategoria = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemGestionarProductos = new javax.swing.JMenuItem();
        jMenuItemAgregarProducto = new javax.swing.JMenuItem();
        jMenuCrearHistorialRegistro = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuCerrarSesion = new javax.swing.JMenu();
        jMenuItemCerrarSesion = new javax.swing.JMenuItem();

        jMenu5.setText("jMenu5");

        jMenu13.setText("jMenu13");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        setPreferredSize(new java.awt.Dimension(100, 40));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenuGestionarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N
        jMenuGestionarUsuario.setText("Usuario");
        jMenuGestionarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuGestionarUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuGestionarUsuario.setPreferredSize(new java.awt.Dimension(100, 40));

        jMenuItem1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gestion.png"))); // NOI18N
        jMenuItem1.setText("Gestionar Usuario");
        jMenuGestionarUsuario.add(jMenuItem1);

        jMenuItemNuevoUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItemNuevoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar-usuario.png"))); // NOI18N
        jMenuItemNuevoUsuario.setText("Nuevo Usuario");
        jMenuItemNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNuevoUsuarioActionPerformed(evt);
            }
        });
        jMenuGestionarUsuario.add(jMenuItemNuevoUsuario);

        jMenuBar1.add(jMenuGestionarUsuario);

        jMenuGestionarCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/categorizacion (1).png"))); // NOI18N
        jMenuGestionarCategorias.setText("Categoria");
        jMenuGestionarCategorias.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuGestionarCategorias.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuGestionarCategorias.setPreferredSize(new java.awt.Dimension(110, 40));

        jMenuItemGestionarCategoria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItemGestionarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        jMenuItemGestionarCategoria.setText("Gestionar Categorias");
        jMenuItemGestionarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGestionarCategoriaActionPerformed(evt);
            }
        });
        jMenuGestionarCategorias.add(jMenuItemGestionarCategoria);

        jMenuItemNuevaCategoria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItemNuevaCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar.png"))); // NOI18N
        jMenuItemNuevaCategoria.setText("Nueva Categoria");
        jMenuItemNuevaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNuevaCategoriaActionPerformed(evt);
            }
        });
        jMenuGestionarCategorias.add(jMenuItemNuevaCategoria);

        jMenuBar1.add(jMenuGestionarCategorias);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caja.png"))); // NOI18N
        jMenu3.setText("Producto");
        jMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenu3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenu3.setPreferredSize(new java.awt.Dimension(100, 40));

        jMenuItemGestionarProductos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItemGestionarProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caja-de-entrega.png"))); // NOI18N
        jMenuItemGestionarProductos.setText("Gestionar Producto");
        jMenuItemGestionarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGestionarProductosActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemGestionarProductos);

        jMenuItemAgregarProducto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItemAgregarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar-producto.png"))); // NOI18N
        jMenuItemAgregarProducto.setText("Agregar Producto");
        jMenuItemAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgregarProductoActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemAgregarProducto);

        jMenuBar1.add(jMenu3);

        jMenuCrearHistorialRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/historial-de-transacciones.png"))); // NOI18N
        jMenuCrearHistorialRegistro.setText("Historial");
        jMenuCrearHistorialRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuCrearHistorialRegistro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuCrearHistorialRegistro.setPreferredSize(new java.awt.Dimension(100, 40));

        jMenuItem8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/historial-de-transacciones.png"))); // NOI18N
        jMenuItem8.setText("Crear Historial de Registro");
        jMenuCrearHistorialRegistro.add(jMenuItem8);

        jMenuBar1.add(jMenuCrearHistorialRegistro);

        jMenuCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar-sesion.png"))); // NOI18N
        jMenuCerrarSesion.setText("Cerrar Sesión");
        jMenuCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuCerrarSesion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuCerrarSesion.setPreferredSize(new java.awt.Dimension(130, 40));

        jMenuItemCerrarSesion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItemCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar-sesion.png"))); // NOI18N
        jMenuItemCerrarSesion.setText("Cerrar Sesión");
        jMenuItemCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCerrarSesionActionPerformed(evt);
            }
        });
        jMenuCerrarSesion.add(jMenuItemCerrarSesion);

        jMenuBar1.add(jMenuCerrarSesion);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemGestionarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGestionarCategoriaActionPerformed
        InterGestionarCategoria interGestionarCategoria = new InterGestionarCategoria();
        jDesktopPane_menu.add(interGestionarCategoria);
        interGestionarCategoria.setVisible(true);
    }//GEN-LAST:event_jMenuItemGestionarCategoriaActionPerformed

    private void jMenuItemNuevaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNuevaCategoriaActionPerformed
        InterCategoria interCategoria = new InterCategoria();
        jDesktopPane_menu.add(interCategoria);
        interCategoria.setVisible(true);
    }//GEN-LAST:event_jMenuItemNuevaCategoriaActionPerformed

    private void jMenuItemAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgregarProductoActionPerformed
        InterProducto interProducto = new InterProducto();
        jDesktopPane_menu.add(interProducto);
        interProducto.setVisible(true);

    }//GEN-LAST:event_jMenuItemAgregarProductoActionPerformed

    private void jMenuItemGestionarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGestionarProductosActionPerformed
        InterGestionarProducto interGestionarProducto = new InterGestionarProducto();
        jDesktopPane_menu.add(interGestionarProducto);
        interGestionarProducto.setVisible(true);
    }//GEN-LAST:event_jMenuItemGestionarProductosActionPerformed

    private void jMenuItemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCerrarSesionActionPerformed
        this.dispose(); // Cerrar la ventana de registro
        new FrmInicio().setVisible(true); // Mostrar la ventana de inicio
    }//GEN-LAST:event_jMenuItemCerrarSesionActionPerformed

    private void jMenuItemNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNuevoUsuarioActionPerformed
        InterNuevoUsuario interNuevoUsuario = new InterNuevoUsuario();
        jDesktopPane_menu.add(interNuevoUsuario);
        interNuevoUsuario.setVisible(true);
    }//GEN-LAST:event_jMenuItemNuevoUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCerrarSesion;
    private javax.swing.JMenu jMenuCrearHistorialRegistro;
    private javax.swing.JMenu jMenuGestionarCategorias;
    private javax.swing.JMenu jMenuGestionarUsuario;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItemAgregarProducto;
    private javax.swing.JMenuItem jMenuItemCerrarSesion;
    private javax.swing.JMenuItem jMenuItemGestionarCategoria;
    private javax.swing.JMenuItem jMenuItemGestionarProductos;
    private javax.swing.JMenuItem jMenuItemNuevaCategoria;
    private javax.swing.JMenuItem jMenuItemNuevoUsuario;
    // End of variables declaration//GEN-END:variables

    
}
